services:
    postgres:
        image: postgres:14.2
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=paymentgatewaydb        
        ports:
          - '5432:5432'
        volumes:           
          # copy the sql script to create tables
          - ./CreatePaymentTable.sql:/docker-entrypoint-initdb.d/CreatePaymentTable.sql